services:
 - docker

install:
 - docker-compose build
 - docker-compose up -d

script:
 - docker ps | grep -q redaxscript
 - docker ps | grep -q smtp
 - docker ps | grep -q mysql
 - docker ps | grep -q pgsql