services:
 - docker

install:
 - docker-compose build
 - docker-compose up -d

script:
 - docker exec redaxscript npm run phpunit-mysql-docker
 - docker exec redaxscript npm run phpunit-pgsql-docker
 - docker exec redaxscript npm run phpunit-sqlite