mysql:
 container_name: mysql
 image: mysql:5.7
 environment:
 - MYSQL_DATABASE=test
 - MYSQL_ROOT_PASSWORD=test

pgsql:
 container_name: pgsql
 image: postgres:11.1
 environment:
 - POSTGRES_DB=test
 - POSTGRES_PASSWORD=test

smtp:
 container_name: smtp
 image: tophfr/mailcatcher

redaxscript:
 container_name: redaxscript
 build: .
 volumes:
 - $PWD/../redaxscript:/var/www/html
 ports:
 - 9000:8000
 links:
 - mysql
 - pgsql
 - smtp
