mysql:
 container_name: mysql
 image: mysql
 environment:
 - MYSQL_DATABASE=test
 - MYSQL_ROOT_PASSWORD=test

pgsql:
 container_name: pgsql
 image: postgres
 environment:
 - POSTGRES_DB=test
 - POSTGRES_PASSWORD=test

smtp:
 container_name: smtp
 image: tophfr/mailcatcher

redaxscript:
 container_name: redaxscript
 build: .
 volumes:
 - $PWD/../redaxscript:/var/www/html
 ports:
 - 8080:80
 links:
 - mysql
 - pgsql
 - smtp
