name: ci

on:
 push:
 pull_request:
 schedule:
 - cron: 0 0 * * *

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - run: docker-compose up -d
  - run: docker-compose ps | grep -q redaxscript
  - run: ocker-compose ps | grep -q mysql
  - run: docker-compose ps | grep -q pgsql
  - run: docker-compose ps | grep -q smtp
